name: Rust

on:
  push:
    branches: [ master, workflow ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        cd contracts
        rustup update stable
        cargo build --release --verbose
    - name: Run tests
      run: |
        cd contracts
        rustup update stable
        cargo +nightly test --no-default-features --features std,ink-experimental-engine --verbose -- --nocapture

