name: Rust

on:
  push:
    branches: [ master, workflow ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Setup Environment
        run: |
          cd contracts
          rustup update stable
          rustup update nightly
          rustup target add wasm32-unknown-unknown --toolchain nightly
          cargo install cargo-tarpaulin